# Generated by Django 4.0 on 2022-10-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=625)),
                ('current_longitude', models.FloatField()),
                ('current_latitude', models.FloatField()),
                ('current_location', models.CharField(max_length=625)),
                ('is_engine_blocked', models.BooleanField()),
                ('current_speed', models.PositiveIntegerField()),
                ('current_sattelite', models.PositiveIntegerField()),
                ('imei', models.PositiveBigIntegerField()),
                ('current_status', models.CharField(max_length=125)),
                ('last_message_timestamp_utc', models.PositiveBigIntegerField()),
                ('last_message_timestamp_txt_utc', models.CharField(max_length=625)),
                ('current_mileage', models.PositiveIntegerField()),
                ('status_charging', models.BooleanField()),
                ('battery_percent', models.PositiveIntegerField()),
                ('network_type', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Телеметрия устройства',
                'verbose_name_plural': 'Телеметрия устройств',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeStampSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_interval', models.PositiveIntegerField(default=10)),
                ('max_interval', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Временная метка',
                'verbose_name_plural': 'Временные метки',
                'ordering': ['-created_at'],
            },
        ),
    ]
