# Generated by Django 4.0 on 2023-01-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehistory',
            name='driver_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
