# Generated by Django 4.0 on 2022-10-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
