# Generated by Django 4.1.6 on 2023-02-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0002_alter_device_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='android_api.data'),
        ),
    ]
