# Generated by Django 4.0 on 2022-10-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0002_alter_device_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
