# Generated by Django 4.0 on 2022-10-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0003_alter_device_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='acceleration_x',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='acceleration_y',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='acceleration_z',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
