# Generated by Django 4.0 on 2022-10-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0004_device_acceleration_x_device_acceleration_y_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='current_latitude',
            new_name='accuracy',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='current_longitude',
            new_name='altitude',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='status_charging',
            new_name='charging',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='current_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='current_mileage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='current_sattelite',
            new_name='satellites',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='current_speed',
            new_name='speed',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='current_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='device',
            name='bearing',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
