# Generated by Django 4.1.6 on 2023-02-06 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0005_alter_allactivitymetrics_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='activity',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='all_activity_metrics',
            field=models.ManyToManyField(null=True, to='android_api.allactivitymetrics'),
        ),
        migrations.AlterField(
            model_name='data',
            name='bearing',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='android_api.bearing'),
        ),
        migrations.AlterField(
            model_name='data',
            name='speed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='android_api.speed'),
        ),
        migrations.AlterField(
            model_name='data',
            name='xy',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='android_api.xy'),
        ),
        migrations.CreateModel(
            name='OkoDriveStatusActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_status', models.CharField(max_length=20)),
                ('device_id', models.ManyToManyField(null=True, to='android_api.device')),
            ],
        ),
    ]
