# Generated by Django 4.0 on 2022-10-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0005_rename_current_latitude_device_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_message_timestamp_txt_utc',
            field=models.CharField(blank=True, max_length=625),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=625),
        ),
    ]
