# Generated by Django 4.1.6 on 2023-02-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0006_alter_data_activity_alter_data_all_activity_metrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okodrivestatusactive',
            name='device_id',
        ),
        migrations.AddField(
            model_name='okodrivestatusactive',
            name='device_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
