# Generated by Django 4.0 on 2022-11-05 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0006_alter_device_last_message_timestamp_txt_utc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='activity_type',
            field=models.CharField(default='', max_length=625),
            preserve_default=False,
        ),
    ]
