# Generated by Django 4.0 on 2022-11-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0007_device_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='imei',
        ),
    ]
