# Generated by Django 4.1.6 on 2023-02-08 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('android_api', '0007_remove_okodrivestatusactive_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('activity_type', models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25)),
                ('okodrive_status', models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], default='ignore', max_length=25)),
                ('state_number', models.CharField(blank=True, max_length=125, null=True)),
                ('speed', models.FloatField()),
                ('bearing', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('all_activity_metrics', models.CharField(max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'История устройства',
                'verbose_name_plural': 'История устройств',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeviceHistory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('activity_type', models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25)),
                ('okodrive_status', models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], default='ignore', max_length=25)),
                ('state_number', models.CharField(blank=True, max_length=125, null=True)),
                ('speed', models.FloatField()),
                ('bearing', models.FloatField()),
                ('time', models.DateTimeField(blank=True, editable=False)),
                ('all_activity_metrics', models.CharField(max_length=25, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical История устройства',
                'verbose_name_plural': 'historical История устройств',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
