# Generated by Django 4.1.6 on 2023-02-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0008_devicehistory_historicaldevicehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicehistory',
            name='state_number',
        ),
        migrations.RemoveField(
            model_name='historicaldevicehistory',
            name='state_number',
        ),
    ]
