# Generated by Django 4.0 on 2022-11-06 10:21

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('android_api', '0008_remove_device_imei'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('device_id', models.IntegerField(blank=True, db_index=True)),
                ('id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=625)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=625)),
                ('is_engine_blocked', models.BooleanField()),
                ('activity_type', models.CharField(max_length=625)),
                ('speed', models.PositiveIntegerField()),
                ('satellites', models.PositiveIntegerField()),
                ('accuracy', models.FloatField()),
                ('bearing', models.FloatField()),
                ('altitude', models.FloatField()),
                ('status', models.CharField(max_length=125)),
                ('last_message_timestamp_utc', models.PositiveBigIntegerField()),
                ('last_message_timestamp_txt_utc', models.CharField(blank=True, max_length=625)),
                ('mileage', models.PositiveIntegerField()),
                ('charging', models.BooleanField()),
                ('battery_percent', models.PositiveIntegerField()),
                ('network_type', models.CharField(blank=True, max_length=12, null=True)),
                ('acceleration_x', models.FloatField()),
                ('acceleration_y', models.FloatField()),
                ('acceleration_z', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user')),
            ],
            options={
                'verbose_name': 'historical Телеметрия устройства',
                'verbose_name_plural': 'historical Телеметрия устройств',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
