# Generated by Django 4.0 on 2022-11-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0009_historicaldevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_engine_blocked',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='is_engine_blocked',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicaldevice',
            name='status',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_message_timestamp_utc',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='last_message_timestamp_utc',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
