# Generated by Django 4.0 on 2022-11-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0010_remove_device_is_engine_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='id',
            field=models.PositiveIntegerField(),
        ),
    ]
