# Generated by Django 4.0 on 2022-11-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0011_alter_device_id_alter_historicaldevice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='HistoricalDevice',
        ),
    ]
