# Generated by Django 4.1.6 on 2023-02-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0011_alter_devicehistory_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.CharField(blank=True, max_length=625, verbose_name='Last message'),
        ),
    ]
