# Generated by Django 4.0 on 2022-11-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0012_alter_device_id_delete_historicaldevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='yandex_link',
            field=models.CharField(blank=True, max_length=625),
        ),
    ]
