# Generated by Django 4.1.6 on 2023-02-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0012_alter_data_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehistory',
            name='speed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='historicaldevicehistory',
            name='speed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
