# Generated by Django 4.0 on 2022-11-12 15:54

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('android_api', '0013_device_yandex_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=625)),
                ('activity_type', models.CharField(max_length=625)),
                ('speed', models.FloatField()),
                ('satellites', models.PositiveIntegerField()),
                ('accuracy', models.FloatField()),
                ('bearing', models.FloatField()),
                ('altitude', models.FloatField()),
                ('last_message_timestamp_utc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_message_timestamp_txt_utc', models.CharField(blank=True, max_length=625)),
                ('charging', models.BooleanField()),
                ('battery_percent', models.PositiveIntegerField()),
                ('network_type', models.CharField(blank=True, max_length=12, null=True)),
                ('yandex_link', models.CharField(blank=True, max_length=625)),
                ('acceleration_x', models.FloatField()),
                ('acceleration_y', models.FloatField()),
                ('acceleration_z', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'История устройства',
                'verbose_name_plural': 'История устройств',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='speed',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='HistoricalDevice',
            fields=[
                ('device_id', models.IntegerField(blank=True, db_index=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('location', models.CharField(blank=True, max_length=625)),
                ('activity_type', models.CharField(max_length=625)),
                ('speed', models.FloatField()),
                ('satellites', models.PositiveIntegerField()),
                ('accuracy', models.FloatField()),
                ('bearing', models.FloatField()),
                ('altitude', models.FloatField()),
                ('last_message_timestamp_utc', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_message_timestamp_txt_utc', models.CharField(blank=True, max_length=625)),
                ('charging', models.BooleanField()),
                ('battery_percent', models.PositiveIntegerField()),
                ('network_type', models.CharField(blank=True, max_length=12, null=True)),
                ('yandex_link', models.CharField(blank=True, max_length=625)),
                ('acceleration_x', models.FloatField()),
                ('acceleration_y', models.FloatField()),
                ('acceleration_z', models.FloatField()),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.user')),
            ],
            options={
                'verbose_name': 'historical Телеметрия устройства',
                'verbose_name_plural': 'historical Телеметрия устройств',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
