# Generated by Django 4.1.6 on 2023-02-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0013_alter_devicehistory_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='custom_utc',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
