# Generated by Django 4.0 on 2022-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0014_devicehistory_remove_device_id_alter_device_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
