# Generated by Django 4.0 on 2022-11-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0016_alter_devicehistory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicehistory',
            options={'ordering': ['-device_id', '-created_at'], 'verbose_name': 'История устройства', 'verbose_name_plural': 'История устройств'},
        ),
        migrations.AddField(
            model_name='devicehistory',
            name='client_timestamp',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='satellites',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='acceleration_x',
            field=models.FloatField(verbose_name='Acceleration X'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='acceleration_y',
            field=models.FloatField(verbose_name='Acceleration Y'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='acceleration_z',
            field=models.FloatField(verbose_name='Acceleration Z'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='accuracy',
            field=models.FloatField(verbose_name='Accuracy'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='activity_type',
            field=models.CharField(max_length=625, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='altitude',
            field=models.FloatField(verbose_name='Altitude'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='battery_percent',
            field=models.PositiveIntegerField(verbose_name='Battery percent'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='bearing',
            field=models.FloatField(verbose_name='Bearing'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='charging',
            field=models.BooleanField(verbose_name='Charging'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Изменено'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='device_id',
            field=models.IntegerField(verbose_name='Device id'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='last_message_timestamp_utc',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Last message timestamp utc'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='location',
            field=models.CharField(blank=True, max_length=625, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='network_type',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Network Type'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='satellites',
            field=models.PositiveIntegerField(verbose_name='Satellites'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='speed',
            field=models.FloatField(verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='yandex_link',
            field=models.CharField(blank=True, max_length=625, verbose_name='Yandex link'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='satellites',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
