# Generated by Django 4.0 on 2022-11-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0017_alter_devicehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='client_timestamp',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='client_timestamp',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='last_message_timestamp_txt_utc',
            field=models.CharField(blank=True, max_length=625, verbose_name='Last message'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='last_message_timestamp_txt_utc',
            field=models.CharField(blank=True, max_length=625, verbose_name='Last message'),
        ),
    ]
