# Generated by Django 4.0 on 2022-11-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0018_device_client_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='state_number',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='state_number',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
