# Generated by Django 4.0 on 2022-11-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0019_device_state_number_historicaldevice_state_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicehistory',
            name='satellites',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Satellites'),
        ),
    ]
