# Generated by Django 4.0 on 2022-11-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0020_alter_devicehistory_satellites'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='app_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('mirror', 'Mirror')], default='phone', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='okodrive_status',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore')], default='ignore', max_length=25),
        ),
        migrations.AddField(
            model_name='devicehistory',
            name='app_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('mirror', 'Mirror')], default='phone', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicehistory',
            name='okodrive_status',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore')], default='ignore', max_length=25),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='app_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('mirror', 'Mirror')], default='phone', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='okodrive_status',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore')], default='ignore', max_length=25),
        ),
        migrations.AlterField(
            model_name='device',
            name='activity_type',
            field=models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='activity_type',
            field=models.CharField(max_length=25, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='activity_type',
            field=models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25),
        ),
    ]
