# Generated by Django 4.0 on 2022-12-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0021_device_app_type_device_okodrive_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='okodrive_status',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], default='ignore', max_length=25),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='okodrive_status',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], default='ignore', max_length=25),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='okodrive_status',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], default='ignore', max_length=25),
        ),
    ]
