# Generated by Django 4.0 on 2022-12-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0023_baseokodrivesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='InVehicleOkoDriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25)),
                ('speed_0', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
                ('speed_between_0_and_6', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
                ('speed_between_6_and_10', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
                ('speed_more_10', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
            ],
            options={
                'verbose_name': 'Настройка для OkoDrive_status по Activity_type (IN_VEHICLE)',
                'verbose_name_plural': 'Настройки для OkoDrive_status по Activity_type (IN_VEHICLE)',
            },
        ),
        migrations.CreateModel(
            name='StillOkoDriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25)),
                ('speed_0', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
                ('speed_between_0_and_6', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
                ('speed_between_6_and_10', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
                ('speed_more_10', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
            ],
            options={
                'verbose_name': 'Настройка для OkoDrive_status по Activity_type (STILL)',
                'verbose_name_plural': 'Настройки для OkoDrive_status по Activity_type (STILL)',
            },
        ),
        migrations.CreateModel(
            name='UnknownOkoDriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25)),
                ('speed_0', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
                ('speed_between_0_and_6', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
                ('speed_between_6_and_10', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
                ('speed_more_10', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12)),
            ],
            options={
                'verbose_name': 'Настройка для OkoDrive_status по Activity_type (UNKNOWN)',
                'verbose_name_plural': 'Настройки для OkoDrive_status по Activity_type (UNKNOWN)',
            },
        ),
        migrations.AlterModelOptions(
            name='baseokodrivesettings',
            options={'verbose_name': 'Настройка для OkoDrive_status по Activity_type (Базовые типы)', 'verbose_name_plural': 'Настройки для OkoDrive_status по Activity_type (Базовые типы)'},
        ),
    ]
