# Generated by Django 4.0 on 2022-12-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0024_invehicleokodrivesettings_stillokodrivesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedIntervalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_interval', models.CharField(max_length=12, verbose_name='Первый интервал')),
                ('second_interval', models.CharField(max_length=12, verbose_name='Второй интервал')),
                ('third_interval', models.CharField(max_length=12, verbose_name='Третий интервал')),
                ('fourth_interval', models.CharField(max_length=12, verbose_name='Четвёртый интервал')),
                ('main_speed_settings', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Настройка промежутков скорости для определения OkoDrive_status',
                'verbose_name_plural': 'Настройки промежутков скорости для определения OkoDrive_status',
            },
        ),
        migrations.RenameField(
            model_name='baseokodrivesettings',
            old_name='speed_0',
            new_name='speed_of_first_interval',
        ),
        migrations.RenameField(
            model_name='baseokodrivesettings',
            old_name='speed_between_0_and_6',
            new_name='speed_of_fourth_interval',
        ),
        migrations.RenameField(
            model_name='baseokodrivesettings',
            old_name='speed_between_6_and_10',
            new_name='speed_of_second_interval',
        ),
        migrations.RenameField(
            model_name='baseokodrivesettings',
            old_name='speed_more_10',
            new_name='speed_of_third_interval',
        ),
        migrations.RenameField(
            model_name='invehicleokodrivesettings',
            old_name='speed_0',
            new_name='speed_of_first_interval',
        ),
        migrations.RenameField(
            model_name='invehicleokodrivesettings',
            old_name='speed_between_0_and_6',
            new_name='speed_of_fourth_interval',
        ),
        migrations.RenameField(
            model_name='invehicleokodrivesettings',
            old_name='speed_between_6_and_10',
            new_name='speed_of_second_interval',
        ),
        migrations.RenameField(
            model_name='invehicleokodrivesettings',
            old_name='speed_more_10',
            new_name='speed_of_third_interval',
        ),
        migrations.RenameField(
            model_name='stillokodrivesettings',
            old_name='speed_0',
            new_name='speed_of_first_interval',
        ),
        migrations.RenameField(
            model_name='stillokodrivesettings',
            old_name='speed_between_0_and_6',
            new_name='speed_of_fourth_interval',
        ),
        migrations.RenameField(
            model_name='stillokodrivesettings',
            old_name='speed_between_6_and_10',
            new_name='speed_of_second_interval',
        ),
        migrations.RenameField(
            model_name='stillokodrivesettings',
            old_name='speed_more_10',
            new_name='speed_of_third_interval',
        ),
        migrations.RenameField(
            model_name='unknownokodrivesettings',
            old_name='speed_0',
            new_name='speed_of_first_interval',
        ),
        migrations.RenameField(
            model_name='unknownokodrivesettings',
            old_name='speed_between_0_and_6',
            new_name='speed_of_fourth_interval',
        ),
        migrations.RenameField(
            model_name='unknownokodrivesettings',
            old_name='speed_between_6_and_10',
            new_name='speed_of_second_interval',
        ),
        migrations.RenameField(
            model_name='unknownokodrivesettings',
            old_name='speed_more_10',
            new_name='speed_of_third_interval',
        ),
    ]
