# Generated by Django 4.0 on 2022-12-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0025_speedintervalsettings_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='speedintervalsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('main_speed_settings', True)), fields=('main_speed_settings',), name='unique_main_speed_settings'),
        ),
    ]
