# Generated by Django 4.0 on 2022-12-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0026_speedintervalsettings_unique_main_speed_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speedintervalsettings',
            options={'ordering': ['-is_main'], 'verbose_name': 'Настройка промежутков скоростей для определения OkoDrive_status', 'verbose_name_plural': 'Настройки промежутков скоростей для определения OkoDrive_status'},
        ),
        migrations.RemoveConstraint(
            model_name='speedintervalsettings',
            name='unique_main_speed_settings',
        ),
        migrations.RenameField(
            model_name='speedintervalsettings',
            old_name='main_speed_settings',
            new_name='is_main',
        ),
        migrations.AddConstraint(
            model_name='speedintervalsettings',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('is_main',), name='unique_is_main'),
        ),
    ]
