# Generated by Django 4.0 on 2022-12-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0027_alter_speedintervalsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_stopped',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicehistory',
            name='is_stopped',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='is_stopped',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseokodrivesettings',
            name='speed_of_first_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для первого интервала'),
        ),
        migrations.AlterField(
            model_name='baseokodrivesettings',
            name='speed_of_fourth_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для четвёртого интервала'),
        ),
        migrations.AlterField(
            model_name='baseokodrivesettings',
            name='speed_of_second_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для второго интервала'),
        ),
        migrations.AlterField(
            model_name='baseokodrivesettings',
            name='speed_of_third_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для третьего интервала'),
        ),
        migrations.AlterField(
            model_name='invehicleokodrivesettings',
            name='speed_of_first_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для первого интервала'),
        ),
        migrations.AlterField(
            model_name='invehicleokodrivesettings',
            name='speed_of_fourth_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для четвёртого интервала'),
        ),
        migrations.AlterField(
            model_name='invehicleokodrivesettings',
            name='speed_of_second_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для второго интервала'),
        ),
        migrations.AlterField(
            model_name='invehicleokodrivesettings',
            name='speed_of_third_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для третьего интервала'),
        ),
        migrations.AlterField(
            model_name='stillokodrivesettings',
            name='speed_of_first_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для первого интервала'),
        ),
        migrations.AlterField(
            model_name='stillokodrivesettings',
            name='speed_of_fourth_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для четвёртого интервала'),
        ),
        migrations.AlterField(
            model_name='stillokodrivesettings',
            name='speed_of_second_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для второго интервала'),
        ),
        migrations.AlterField(
            model_name='stillokodrivesettings',
            name='speed_of_third_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для третьего интервала'),
        ),
        migrations.AlterField(
            model_name='unknownokodrivesettings',
            name='speed_of_first_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для первого интервала'),
        ),
        migrations.AlterField(
            model_name='unknownokodrivesettings',
            name='speed_of_fourth_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для четвёртого интервала'),
        ),
        migrations.AlterField(
            model_name='unknownokodrivesettings',
            name='speed_of_second_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для второго интервала'),
        ),
        migrations.AlterField(
            model_name='unknownokodrivesettings',
            name='speed_of_third_interval',
            field=models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для третьего интервала'),
        ),
    ]
