# Generated by Django 4.0 on 2022-12-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0028_device_is_stopped_devicehistory_is_stopped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='error_name',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='error_name',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car')], max_length=12, null=True),
        ),
    ]
