# Generated by Django 4.0 on 2022-12-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0029_device_error_name_historicaldevice_error_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehistory',
            name='error_name',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car')], max_length=12, null=True),
        ),
    ]
