# Generated by Django 4.0 on 2022-12-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0030_devicehistory_error_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUTCTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_utc', models.CharField(max_length=2, verbose_name='Текущее значение UTC')),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='error_name',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('none', 'None')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='error_name',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('none', 'None')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='error_name',
            field=models.CharField(blank=True, choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('none', 'None')], max_length=12, null=True),
        ),
    ]
