# Generated by Django 4.0 on 2022-12-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0031_currentutctime_alter_device_error_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='driver_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_telegram_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicehistory',
            name='driver_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicehistory',
            name='is_telegram_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='driver_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='is_telegram_activated',
            field=models.BooleanField(default=False),
        ),
    ]
