# Generated by Django 4.0 on 2022-12-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0032_device_driver_id_device_is_telegram_activated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnBicycleOkoDriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25)),
                ('speed_of_first_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для первого интервала')),
                ('speed_of_second_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для второго интервала')),
                ('speed_of_third_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для третьего интервала')),
                ('speed_of_fourth_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для четвёртого интервала')),
            ],
            options={
                'verbose_name': 'Настройка для OkoDrive_status по Activity_type (ON_BICYCLE)',
                'verbose_name_plural': 'Настройки для OkoDrive_status по Activity_type (ON_BICYCLE)',
            },
        ),
        migrations.CreateModel(
            name='OnFootOkoDriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25)),
                ('speed_of_first_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для первого интервала')),
                ('speed_of_second_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для второго интервала')),
                ('speed_of_third_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для третьего интервала')),
                ('speed_of_fourth_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для четвёртого интервала')),
            ],
            options={
                'verbose_name': 'Настройка для OkoDrive_status по Activity_type (ON_FOOT)',
                'verbose_name_plural': 'Настройки для OkoDrive_status по Activity_type (ON_FOOT)',
            },
        ),
        migrations.CreateModel(
            name='RunningOkoDriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25)),
                ('speed_of_first_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для первого интервала')),
                ('speed_of_second_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для второго интервала')),
                ('speed_of_third_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для третьего интервала')),
                ('speed_of_fourth_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для четвёртого интервала')),
            ],
            options={
                'verbose_name': 'Настройка для OkoDrive_status по Activity_type (RUNNING)',
                'verbose_name_plural': 'Настройки для OkoDrive_status по Activity_type (RUNNING)',
            },
        ),
        migrations.CreateModel(
            name='TiltingOkoDriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25)),
                ('speed_of_first_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для первого интервала')),
                ('speed_of_second_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для второго интервала')),
                ('speed_of_third_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для третьего интервала')),
                ('speed_of_fourth_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для четвёртого интервала')),
            ],
            options={
                'verbose_name': 'Настройка для OkoDrive_status по Activity_type (TILTING)',
                'verbose_name_plural': 'Настройки для OkoDrive_status по Activity_type (TILTING)',
            },
        ),
        migrations.CreateModel(
            name='WalkingOkoDriveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('IN_VEHICLE', 'In Vehicle'), ('ON_BICYCLE', 'On Bicycle'), ('ON_FOOT', 'On Foot'), ('WALKING', 'Walking'), ('RUNNING', 'Running'), ('STILL', 'Still'), ('TILTING', 'Tilting'), ('UNKNOWN', 'Unknown'), ('None', 'None')], max_length=25)),
                ('speed_of_first_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для первого интервала')),
                ('speed_of_second_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для второго интервала')),
                ('speed_of_third_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для третьего интервала')),
                ('speed_of_fourth_interval', models.CharField(choices=[('in_car', 'In Car'), ('out_car', 'Out Car'), ('ignore', 'Ignore'), ('error', 'Error')], max_length=12, verbose_name='Статус для четвёртого интервала')),
            ],
            options={
                'verbose_name': 'Настройка для OkoDrive_status по Activity_type (WALKING)',
                'verbose_name_plural': 'Настройки для OkoDrive_status по Activity_type (WALKING)',
            },
        ),
    ]
