# Generated by Django 4.0 on 2022-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0033_onbicycleokodrivesettings_onfootokodrivesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='driver_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devicehistory',
            name='driver_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='driver_id',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('device_id', 'driver_id'), name='unique_driver_telegramm'),
        ),
    ]
