# Generated by Django 4.0 on 2022-12-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0034_alter_device_driver_id_alter_devicehistory_driver_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='unique_driver_telegramm',
        ),
    ]
