# Generated by Django 4.0 on 2022-12-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android_api', '0035_remove_device_unique_driver_telegramm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(verbose_name='Device id')),
                ('is_telegram_activated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Подтверждение регистрации в телеграме',
                'verbose_name_plural': 'Подтверждение регистраций в телеграме',
            },
        ),
    ]
